### ISSUE TITLE
Json deserialize error

### ISSUE THREAD

**Issue by minorsecond** [v1nsai/red2lem#3]
I just tried this on the /r/gis subreddit to bring it over the lemmy gis community and get this error for every post it tries to copy:

`pythorhead.requestor - ERROR - Error encountered while Request.POST: Json deserialize error: invalid type: null, expected i32 at line 1 column 21`

Then, at the end, I get `TypeError: Object of type bytes is not JSON serializable`

Here's the stacktrace for the last error:

```
Traceback (most recent call last):
  File "/home/rwardrup/red2lem/bot.py", line 87, in <module>
    lemmy.post.create( community_id=community_id, name=title, url=media_url, body=media_content )
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/pythorhead/post.py", line 122, in create
    return self._requestor.request(Request.POST, "/post", json=new_post)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/pythorhead/requestor.py", line 56, in request
    r = REQUEST_MAP[method](f"{self._auth.api_base_url}{endpoint}", **kwargs)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/rwardrup/miniconda3/envs/bot/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by minorsecond** [comment]
This was a stupid user error - I wasn't careful about the community name.
